apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/core: capi-operator
  name: capi-operator-serving-cert
  namespace: '{{ .Release.Namespace }}'
spec:
  dnsNames:
  - capi-operator-webhook-service.{{ .Release.Namespace }}.svc
  - capi-operator-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: capi-operator-selfsigned-issuer
  secretName: capi-operator-webhook-service-cert
