{{- if .Values.pullJsonSecret }}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.pullJsonSecret }}
kind: Secret
metadata:
  name: image-pull-secret
  namespace: capa-system
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "2"
type: kubernetes.io/dockerconfigjson
{{- end }}
