apiVersion: v1
kind: Namespace
metadata:
  annotations:
    "argocd.argoproj.io/sync-wave": "1"
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "1"
  name: capi-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    "argocd.argoproj.io/sync-wave": "1"
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "1"
  labels:
    cluster.x-k8s.io/provider: cluster-api
    clusterctl.cluster.x-k8s.io: ""
  name: capi-admin-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: capi-manager
  namespace: capi-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "2"
    "argocd.argoproj.io/sync-wave": "2"
  name: cluster-api
  namespace: capi-system
spec:
  manager:
    featureGates:
      MachinePool: true
      ClusterTopology: false
      ClusterResourceSet: true
  deployment:
    {{- with .Values.imagePullSecrets }}
    imagePullSecrets:
    {{- toYaml . | nindent 8 }}
    {{- end }}
    containers:
      - imageUrl: registry.redhat.io/openshift4/ose-cluster-api-rhel9:{{ .Values.image.manager.tag }}
        name: manager
        command:
          - /bin/cluster-api-controller-manager
          
